### ISSUE TITLE
Login with SSO

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/wordpress-sso-plugin#11]
What should I do next when I click the "AESIR Login" button @jatitoam 
[image](https://user-images.githubusercontent.com/79819354/223315260-35375ad9-9a7a-4af9-808d-50de76193c8e.png)

**Comment by jatitoam** [comment]
can you please attend Vladimir?

**Comment by shandak** [comment]
Make sure you configured the plugin before use. There are multiple options that have to be set before. 
And we need updated js lib too @jatitoam https://github.com/aesirxio/wordpress-sso-plugin/pull/10

**Comment by huynhngocgiau** [comment]
It worked so I will close this issue
